lang_detect: "models/lang_detect_v10.ftz"
min_text_length: 20
parse_links: false
save_texts: false
compute_nasty: true
category_models: [
    {
        language: LN_RU
        path: "models/ru_cat_v5.ftz"
    },
    {
        language: LN_EN
        path: "models/en_cat_v5.ftz"
    }
]
embedders: [
    {
        type: ET_FASTTEXT
        language: LN_RU
        embedding_key: EK_FASTTEXT_CLASSIC
        vector_model_path: "models/ru_vectors_v3.bin"
        aggregation_mode: AM_MATRIX
        embedder_field: EF_ALL
        max_words: 150
        model_path: "models/ru_sentence_embedder_v3.pt"
    },
    {
        type: ET_FASTTEXT
        language: LN_EN
        embedding_key: EK_FASTTEXT_CLASSIC
        vector_model_path: "models/en_vectors_v3.bin"
        aggregation_mode: AM_MATRIX
        embedder_field: EF_ALL
        max_words: 150
        model_path: "models/en_sentence_embedder_v3.pt"
    }
]
