clusterings: [
    {
        language: LN_RU
        small_threshold: 0.045
        small_cluster_size: 10
        medium_threshold: 0.04
        medium_cluster_size: 20
        large_threshold: 0.035
        large_cluster_size: 30
        chunk_size: 15000
        intersection_size: 5000
        use_timestamp_moving: false
        ban_same_hosts: true
        embedding_keys_weights: [
            {
                embedding_key: EK_FASTTEXT_CLASSIC
                weight: 1.0
            }
        ]
    },
    {
        language: LN_EN
        small_threshold: 0.045
        small_cluster_size: 10
        medium_threshold: 0.04
        medium_cluster_size: 20
        large_threshold: 0.035
        large_cluster_size: 30
        chunk_size: 15000
        intersection_size: 5000
        use_timestamp_moving: false
        ban_same_hosts: true
        embedding_keys_weights: [
            {
                embedding_key: EK_FASTTEXT_CLASSIC
                weight: 1.0
            }
        ]
    }
]
iter_timestamp_percentile: 0.99
hosts_rating: "models/pagerank_rating.txt"
alexa_rating: "models/alexa_rating_4_fixed.txt"
