threads: 4

db_path: "sample.db"
db_max_open_files: 1024

skip_irrelevant_docs: false
clusterer_sleep: 1000 # milliseconds

annotator_config_path: "configs/annotator.pbtxt"
clusterer_config_path: "configs/clusterer.pbtxt"
